### ISSUE TITLE
Cant compile project

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [teppyboy/SirHurtAPI#4]
So, i wanted to try out this API for making my custom ui for SirHurt, but when i try to compile it on Visual Studio 2019 Community, it outputs that the compiling was successful but, no files are created, i already tried compiling without this API, and guess what, it worked, any fix?

**Comment by teppyboy** [comment]
Btw when u compile with SirHurtAPI did you set SirHurtAPI Copy Local property to true?
also if yes then try to test if it work...

sorry for late reply bc im watching a lot of anime lol

**Comment by xXTevinOfficialXx** [comment]
I found out what it was, i didn't have .NET Framework 4.8 dev pack so it wasn't allowing me to set the project framework to 4.8, thanks for the help anyways

**Comment by teppyboy** [comment]
Fixed now
